version: '3.9'

services:
  jira-backend:
    restart: always
    build: ./server
    container_name: jira-backend
    ports:
      - "3000:8001"
    environment:
      - DATABASE_URL="mongodb+srv://admin:fxrog96tV3nt93wF@jiraclone.zfma8xu.mongodb.net/jiraClone"
  jira-frontend:
    restart: always
    build: ./ui
    container_name: jira-frontend
    environment:
      - VITE_BACKEND_URL="http://localhost:3000"
    links:
      - "jira-backend:backend"
    ports:
      - "3001:80"
